require: rubocop-sketchup

AllCops:
  DisabledByDefault: true # TODO: Cleanup regular RuboCop warnings.
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
  - src/*/vendor/**/*
  - tools/**/*
  NewCops: enable
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
    - Gemfile
    - profiling/**/*
    - skippy/**/*
    - tests/**/*
    - tools/**/*
  TargetRubyVersion: 2.0


SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

SketchupRequirements:
  Enabled: true

SketchupSuggestions:
  Enabled: true

SketchupBugs:
  Enabled: true
