#inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5 # 2.0 not supported any more.

# Too noisy...
Metrics/AbcSize:
  Enabled: false

# Tests should have not upper size limit.
Metrics/ClassLength:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'
    - 'src/tt_shadow_texture/shadow_render_tool.rb' # TODO

# Too noisy...
Metrics/CyclomaticComplexity:
  Enabled: false

# Allowing for a few more lines than the default 10.
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'src/tt_shadow_texture/shadow_render_tool.rb' # TODO

# Too noisy...
Metrics/PerceivedComplexity:
  Enabled: false

# I will align my arrays as I please!
Layout/AlignArray:
  Enabled: false

# It's ok to use {...} for multi-line blocks.
Style/BlockDelimiters:
  Enabled: false

# Tests follow a different naming convention.
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Compact style is fine.
Style/ClassAndModuleChildren:
  Enabled: false

# No need for a doc-block for each class/module.
Style/Documentation:
  Enabled: false

# Tests follow a different naming convention.
Naming/FileName:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# It's ok to use double empty lines for "paragraphs".
Layout/EmptyLines:
  Enabled: false

# Extra space is fine.
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Extra space is fine.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# RuboCop - why you hate white-space?
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Let git handle and normalize end of line. Eaiser for Windows.
Layout/EndOfLine:
  Enabled: false

# Some times it simply reads better to not have a modifier conditional.
Style/IfUnlessModifier:
  Enabled: false

# This project use 4 spaces for continuity-lines.
Layout/IndentArray:
  Enabled: false

# This project use 4 spaces for continuity-lines.
Layout/IndentHash:
  Enabled: false

# Root extension file got an unusual indentation. That's fine.
# This is very particular to my TT::Plugin::Extension name scheme.
# Whoever might read this; the ::Plugin:: part is legacy naming I now regret.
Layout/IndentationWidth:
  Exclude:
    - 'src/*.rb'
    - 'profiling/PR_ShadowRender.rb' # TODO

# Tool classes must use the SketchUp API method names.
Naming/MethodName:
  Exclude:
    - '**/*_tool.rb'

# No need to force `.zero` over `== 0`
Style/NumericPredicate:
  Enabled: false

# It's fine to refer to self.
Style/RedundantSelf:
  Enabled: false

# Space is fine.
#Style/SpaceInsideBrackets:
#  Enabled: false

# It's fine to have trailing comma, makes adding/removing items easier.
Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
